 CREATE SCHEMA PORTALDB;

CREATE TABLE `PORTALDB`.`user` (
	`PKID` INT NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(400),
	`LAST_NAME` VARCHAR(400),
	`PASSWORD` VARCHAR(400),
	`EMAIL` VARCHAR(400) NOT NULL,
	PRIMARY KEY (`PKID`)
);


