CREATE SCHEMA PORTALDB;

CREATE TABLE `PORTALDB`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PORTALDB`.`user` (
	`PKID` INT NOT NULL AUTO_INCREMENT,
	`FIRST_NAME` VARCHAR(400),
	`LAST_NAME` VARCHAR(400),
	`PASSWORD` VARCHAR(400),
	`EMAIL` VARCHAR(400) NOT NULL,
	`ROLE_ID` VARCHAR(100) NOT NULL,
  	FOREIGN KEY (ROLE_ID) REFERENCES `PORTALDB`.`ROLE`(ID),
	PRIMARY KEY (`PKID`)
);

CREATE TABLE `PORTALDB`.`JOBS` (
	`PKID` INT NOT NULL AUTO_INCREMENT,
	`JOB_CATEGORY` VARCHAR(400) NOT NULL,
	`JOB_CODE` VARCHAR(400) NOT NULL,
	`JOB_TITLE` VARCHAR(400) NOT NULL,
	`JOB_LOCATION` VARCHAR(400) NOT NULL,
	`JOB_TYPE` VARCHAR(400) NOT NULL,
	`JOB_REQUIREMENTS` VARCHAR(10000) NOT NULL,
	`JOB_DESCRIPTION` VARCHAR(10000) NOT NULL,
	`HOURS` VARCHAR(40) NOT NULL,
	`RATE` VARCHAR(40) NOT NULL,
	`ACTIVE` VARCHAR(20) NOT NULL,
	
	PRIMARY KEY (`JOB_CODE`)
);

CREATE TABLE `PORTALDB`.`JOB_APPLICATION` (
	`PKID` INT NOT NULL AUTO_INCREMENT,
	`USER_ID` INT,
	`JOB_CODE` VARCHAR(400),
	`RESUME` MEDIUMBLOB,
	`COVER_LETTER` VARCHAR(3000),
	`APPLICATION_DATE` DATE,
	`APPLICATION_STATUS` VARCHAR(40),
	
  	FOREIGN KEY (USER_ID) REFERENCES `PORTALDB`.`USER`(PKID),
  	FOREIGN KEY (JOB_CODE) REFERENCES `PORTALDB`.`JOBS`(JOB_CODE),
	PRIMARY KEY (`PKID`)
);



