package com.java.portal.entity;
// Generated Oct 17, 2016 1:27:18 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactMessage generated by hbm2java
 */
@Entity
@Table(name = "CONTACT_MESSAGE", schema = "PORTALDB", catalog = "PORTALDB")
public class ContactMessage implements java.io.Serializable {

	private Integer pkid;
	private String firstName;
	private String lastName;
	private String company;
	private String email;
	private String address;
	private String city;
	private String state;
	private String comments;
	private Date submittedDate;

	public ContactMessage() {
	}

	public ContactMessage(String email) {
		this.email = email;
	}

	public ContactMessage(String firstName, String lastName, String company, String email, String address, String city,
			String state, String comments, Date submittedDate) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.company = company;
		this.email = email;
		this.address = address;
		this.city = city;
		this.state = state;
		this.comments = comments;
		this.submittedDate = submittedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PKID", unique = true, nullable = false)
	public Integer getPkid() {
		return this.pkid;
	}

	public void setPkid(Integer pkid) {
		this.pkid = pkid;
	}

	@Column(name = "FIRST_NAME", length = 400)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 400)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "COMPANY", length = 400)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "EMAIL", nullable = false, length = 400)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADDRESS", length = 400)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", length = 400)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "STATE", length = 400)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "COMMENTS", length = 10000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMITTED_DATE", length = 8)
	public Date getSubmittedDate() {
		return this.submittedDate;
	}

	public void setSubmittedDate(Date submittedDate) {
		this.submittedDate = submittedDate;
	}

}
