package com.java.portal.entity;
// Generated Sep 20, 2016 3:09:31 PM by Hibernate Tools 4.3.1.Final

import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplication generated by hbm2java
 */
@Entity
@Table(name = "JOB_APPLICATION", schema = "PORTALDB", catalog = "PORTALDB")
public class JobApplication implements java.io.Serializable {

	private Integer pkid;
	private Jobs jobs;
	private User user;
	private Blob resume;
	private String coverLetter;
	private Date applicationDate;
	private String applicationStatus;

	public JobApplication() {
	}

	public JobApplication(Jobs jobs, User user, Blob resume, String coverLetter, Date applicationDate,
			String applicationStatus) {
		this.jobs = jobs;
		this.user = user;
		this.resume = resume;
		this.coverLetter = coverLetter;
		this.applicationDate = applicationDate;
		this.applicationStatus = applicationStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PKID", unique = true, nullable = false)
	public Integer getPkid() {
		return this.pkid;
	}

	public void setPkid(Integer pkid) {
		this.pkid = pkid;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_CODE")
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_ID")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "RESUME")
	public Blob getResume() {
		return this.resume;
	}

	public void setResume(Blob resume) {
		this.resume = resume;
	}

	@Column(name = "COVER_LETTER", length = 3000)
	public String getCoverLetter() {
		return this.coverLetter;
	}

	public void setCoverLetter(String coverLetter) {
		this.coverLetter = coverLetter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPLICATION_DATE", length = 8)
	public Date getApplicationDate() {
		return this.applicationDate;
	}

	public void setApplicationDate(Date applicationDate) {
		this.applicationDate = applicationDate;
	}

	@Column(name = "APPLICATION_STATUS", length = 40)
	public String getApplicationStatus() {
		return this.applicationStatus;
	}

	public void setApplicationStatus(String applicationStatus) {
		this.applicationStatus = applicationStatus;
	}

}
