package com.java.portal.entity;
// Generated Sep 20, 2016 3:09:31 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "JOBS", schema = "PORTALDB", catalog = "PORTALDB")
public class Jobs implements java.io.Serializable {

	private String jobCode;
	private int pkid;
	private String jobCategory;
	private String jobTitle;
	private String jobLocation;
	private String jobType;
	private String jobRequirements;
	private String jobDescription;
	private String hours;
	private String rate;
	private String active;
	private String jobStatus;
	private Set<JobApplication> jobApplications = new HashSet<JobApplication>(0);

	public Jobs() {
	}

	public Jobs(int pkid, String jobCategory, String jobTitle, String jobLocation, String jobType,
			String jobRequirements, String jobDescription, String hours, String rate, String active, String jobStatus, String jobCode) {
		this.pkid = pkid;
		this.jobCategory = jobCategory;
		this.jobTitle = jobTitle;
		this.jobLocation = jobLocation;
		this.jobType = jobType;
		this.jobRequirements = jobRequirements;
		this.jobDescription = jobDescription;
		this.hours = hours;
		this.rate = rate;
		this.active = active;
		this.jobStatus = jobStatus;
		this.jobCode = jobCode;
	}

	public Jobs(int pkid, String jobCategory, String jobTitle, String jobLocation, String jobType,
			String jobRequirements, String jobDescription, String hours, String rate, String active, String jobStatus,
			Set<JobApplication> jobApplications) {
		this.pkid = pkid;
		this.jobCategory = jobCategory;
		this.jobTitle = jobTitle;
		this.jobLocation = jobLocation;
		this.jobType = jobType;
		this.jobRequirements = jobRequirements;
		this.jobDescription = jobDescription;
		this.hours = hours;
		this.rate = rate;
		this.active = active;
		this.jobStatus = jobStatus;
		this.jobApplications = jobApplications;
	}

	@Id
	@Column(name = "JOB_CODE", unique = true, nullable = false, length = 400, columnDefinition="VARCHAR(400)")
	public String getJobCode() {
		return this.jobCode;
	}

	public void setJobCode(String jobCode) {
		this.jobCode = jobCode;
	}

	@Column(name = "PKID", nullable = false)
	public int getPkid() {
		return this.pkid;
	}

	public void setPkid(int pkid) {
		this.pkid = pkid;
	}

	@Column(name = "JOB_CATEGORY", nullable = false, length = 400)
	public String getJobCategory() {
		return this.jobCategory;
	}

	public void setJobCategory(String jobCategory) {
		this.jobCategory = jobCategory;
	}

	@Column(name = "JOB_TITLE", nullable = false, length = 400)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "JOB_LOCATION", nullable = false, length = 400)
	public String getJobLocation() {
		return this.jobLocation;
	}

	public void setJobLocation(String jobLocation) {
		this.jobLocation = jobLocation;
	}

	@Column(name = "JOB_TYPE", nullable = false, length = 400)
	public String getJobType() {
		return this.jobType;
	}

	public void setJobType(String jobType) {
		this.jobType = jobType;
	}

	@Column(name = "JOB_REQUIREMENTS", nullable = false, length = 10000)
	public String getJobRequirements() {
		return this.jobRequirements;
	}

	public void setJobRequirements(String jobRequirements) {
		this.jobRequirements = jobRequirements;
	}

	@Column(name = "JOB_DESCRIPTION", nullable = false, length = 10000)
	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	@Column(name = "HOURS", nullable = false, length = 40)
	public String getHours() {
		return this.hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

	@Column(name = "RATE", nullable = false, length = 40)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	@Column(name = "ACTIVE", nullable = false, length = 20)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "JOB_STATUS", nullable = false, length = 20)
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobApplication> getJobApplications() {
		return this.jobApplications;
	}

	public void setJobApplications(Set<JobApplication> jobApplications) {
		this.jobApplications = jobApplications;
	}

}
